//
//  System Name : Mage's Private Sanctum
//     Filename :acr_s0_glyph_onexit
//      Version : 0.1
//         Date : 3/17/23
//       Author : Wynna
//
//  Description
//  This script handles on exit actions for the area of effect Glyph of Warding.
//  It is not updated in ACR updates.
//
//  Revision History
////////////////////////////////////////////////////////////////////////////////

//	Wynna - 3/17/2023

////////////////////////////////////////////////////////////////////////////////
// Includes ////////////////////////////////////////////////////////////////////
#include "acr_trigger_i"

/* Dummy onexit for glyph of warding object

*/